### ISSUE TITLE
CMakeLists.txt: Imported target "aws-cpp-sdk-core" includes non-existent path

### ISSUE THREAD

**Issue by josefernandez91** [Skarlso/cpp-hosting#5]
I'm having a problem with the compilation, could you help me?

 Imported target "aws-cpp-sdk-core" includes non-existent path
    "/opt/iway/deps/aws-sdk-cpp/aws-cpp-sdk-core/include"
  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
  * The path was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and references files it does not
  provide.

![aws](https://cloud.githubusercontent.com/assets/14926548/22517256/56e1aae2-e887-11e6-875a-f2cf661047db.png)

CMakeList.txt: 
  if (DEFINED ENV{AWS_SDK_PATH})
       set(AWS_SDK_PATH "$ENV{AWS_SDK_PATH}/build")
   else()
       set(AWS_SDK_PATH "${CMAKE_CURRENT_SOURCE_DIR}/aws-sdk-cpp/build")
   endif()
   
  set(aws-sdk-cpp_DIR ${AWS_SDK_PATH})
  find_package(aws-sdk-cpp)

target_link_libraries(aws
aws-cpp-sdk-core)

---------------------------------------------

To compile aws use your script prepare-aws-sdk.sh

**Comment by Skarlso** [comment]
@josefernandez91 Damn! Github didn't send me anything about this issue. :( I'm so sorry mate I didn't notice it. 

Is it still relevant for you?

I switched over to Go after a while, because the CPP AWS SDK is just reeeeeeaaalllly hard to get by with. :)
